### ISSUE TITLE
Margins too wide on smaller displays

### ISSUE THREAD

**Issue by HarvsG** [femto-code/logseq-one-theme#1]
Thank you for making this theme, it is easily my favourite logseq theme.
I copied and pasted the the main.css contents onto my android device to test the theme. However I found that it added wide margins to each page and so really reduced the screen real-estate for text. It would be great if the margins could be reduced on small devices. 
(I also tried main2.css)

**Comment by femto-code** [comment]
@HarvsG Glad to hear, thanks for your feedback! I really appreciate it!

In fact I haven't tested the layout on mobile devices yet. I'll investigate the page margin issues ASAP and will submit a new version soon. Will let you know when the release is available.

Thanks again for reporting. Feel free to report any other issues!

**Comment by femto-code** [comment]
Sorry for the delay, being very busy atm. I will work on a fix very soon.

**Comment by HarvsG** [comment]
No worries, I know what it's like trying to maintain open source stuff when you have a full life!
