### ISSUE TITLE
Top Icons became light after Logseq 0.10.7 update

### ISSUE THREAD

**Issue by redgallows** [femto-code/logseq-one-theme#3]
First of all, I loved the One Theme you made.

I noticed the icons on the top of the Logseq window became so "light" (in the dark mode) after Logseq 0.10.7 update. That makes it so difficult to see.
Please see below the screenshot. It happends on both Windows and macOS version of Logseq. 

![image](https://github.com/femto-code/logseq-one-theme/assets/32216652/8fd7e5c6-a412-461b-a7fa-0e28703c3442)

Could you please take a look?

Thank you.

**Comment by femto-code** [comment]
Thanks very much @redgallows for reporting!

I've noticed the bugs, unfortuantely the Logseq devs broke the styleguide again. I am already working on making the theme work in v0.10.7.

Hang tight, release will be there soon!

**Comment by redgallows** [comment]
Thank you so much for the prompt response and action.
Looking forward the update.

**Comment by femto-code** [comment]
Hi @redgallows ! I have released a quick bug-fix release which recovers the top bar icons. There will be more fixes coming very soon.

https://github.com/femto-code/logseq-one-theme/releases/tag/v0.2.2

**Comment by redgallows** [comment]
Thank you so much for the quick fix.
