### ISSUE TITLE
Selection is invisible in completion menu

### ISSUE THREAD

**Issue by freijon** [femto-code/logseq-one-theme#4]
When opening the completion menu (e.g. by typing '/') I don't see the selected menu entry. It seems to have the same color as the rest of the menu?

![image](https://github.com/femto-code/logseq-one-theme/assets/1387831/5508eefc-b6bf-4a39-9bc1-8f560d3cfb69)

**Comment by femto-code** [comment]
Hi @freijon ! Thanks for reporting. I'll look into this asap.

**Comment by femto-code** [comment]
Assuming you have the latest Logseq and theme version this might be an issue with accent colors.

In Settings, have you set the accent color to the "Logseq classical color"? If so, this might be the reason. Unfortunately, this option is not supported by One Theme at the moment. Please set it to disabled (see screenshot), the theme will work fine afterwards.

![image](https://github.com/femto-code/logseq-one-theme/assets/59444046/3fb8ff31-8967-4499-8024-f4fd3636ac4f)

Let me know if that fixes your issue.

**Comment by freijon** [comment]
Hello @femto-code 

Thanks, that was a good hint. For me, this setting was completely unset:
![image](https://github.com/femto-code/logseq-one-theme/assets/1387831/ede8142e-b905-4444-ac57-a42fa5e7ce08)

I now set it to "Cancel accent color" like in your screenshot and now I do see the selected entry in the menus:
![image](https://github.com/femto-code/logseq-one-theme/assets/1387831/9d5e703a-d586-449f-bea4-ca58aa067180)

Problem solved 👍🏻

**Comment by femto-code** [comment]
Interesting thing. Unfortunately, Logseq has a lot of buggy behavior.

Anyway, glad to hear, it's solved.
