### ISSUE TITLE
Selection highlighting Dark Theme Dropdown Menu

### ISSUE THREAD

**Issue by HarvsG** [femto-code/logseq-one-theme#5]
When in darkmode you cant see which menu row is selected
![image](https://github.com/femto-code/logseq-one-theme/assets/11440490/65b9fa95-e3db-4413-b451-52c8b8033871)
Contrast this to light mode:
![image](https://github.com/femto-code/logseq-one-theme/assets/11440490/d61a2bde-350e-4a83-8c17-2f91594b9d15)

v0.3.1

**Comment by HarvsG** [comment]
Also the menu icons are hard to see:
![image](https://github.com/femto-code/logseq-one-theme/assets/11440490/e215df3b-b3d1-43da-8e0e-185ee650974b)

**Comment by femto-code** [comment]
Thanks for reporting @HarvsG !

Have you set the accent color option to disabled?

![311193114-3fb8ff31-8967-4499-8024-f4fd3636ac4f.png](https://github.com/femto-code/logseq-one-theme/assets/59444046/6231024f-d64c-4cfa-b736-147f669afe11)


Explanation here:

https://github.com/femto-code/logseq-one-theme/issues/4#issuecomment-1985396560

**Comment by HarvsG** [comment]
Thank you for your help once again. I can confirm that cancelling the accent colour fixed the issue
![image](https://github.com/femto-code/logseq-one-theme/assets/11440490/89f451a9-da87-452f-a084-45a211429d49)

![image](https://github.com/femto-code/logseq-one-theme/assets/11440490/dbf8fca4-45a7-44c1-b7c1-a70229c0c33b)

**Comment by femto-code** [comment]
@HarvsG I'm glad to hear. I will be working on supporting accent colors soon.
